moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01
  execution_duration_monitoring: false

moveit_simple_controller_manager:
  controller_names:
    - scaled_joint_trajectory_controller
    # - joint_trajectory_controller

  scaled_joint_trajectory_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - ur1_shoulder_pan_joint
      - ur1_shoulder_lift_joint
      - ur1_elbow_joint
      - ur1_wrist_1_joint
      - ur1_wrist_2_joint
      - ur1_wrist_3_joint

  # joint_trajectory_controller:
  #   action_ns: follow_joint_trajectory
  #   type: FollowJointTrajectory
  #   default: false
  #   joints:
  #     - ur1_shoulder_pan_joint
  #     - ur1_shoulder_lift_joint
  #     - ur1_elbow_joint
  #     - ur1_wrist_1_joint
  #     - ur1_wrist_2_joint
  #     - ur1_wrist_3_joint
